name: mantidimaging
channels:
  - mantid
  - dtasev
  - astra-toolbox/label/dev
  - conda-forge
  - defaults
dependencies:
  - mantidimaging==2.0.0
  - python=3.7.*
  - pip=20.3.3
  - sarepy=2020.07
  - astra-toolbox=1.9.9.dev4
  - pip:
      - pyqt5==5.15
      - pyqtgraph==0.11
      - hazelnut==0.4.1
      - gitpython==3.1.11
      - mock==4.0.3
      - psutil==5.7.3
      - isort==5.6.4
      - sharedarray==3.2.1
