name: mantidimaging-nightly
channels:
  - mantid/label/unstable
  - dtasev
  - astra-toolbox/label/dev
  - conda-forge
  - defaults
# Dependencies that can be installed with conda should be in conda/meta.yaml
dependencies:
  - mantidimaging
  - pip
  - pip:
      - pyqt6>=6.0.3,<6.1
      - pyqtgraph>=0.12.1,<0.13
      - jenkspy==0.2.0
