name: mantidimaging-dev-cil
channels:
  - mantid/label/unstable
  - dtasev
  - astra-toolbox/label/dev
  - conda-forge
  - ccpi
  - defaults
dependencies:
  #- mantidimaging>=2.1.0rc
  - python=3.8.*
  - pip
  - astropy=4.2
  - scipy=1.5.3
  - scikit-image=0.17.2
  #- numpy=1.19.4
  - numpy>=1.18.1
  - tomopy=1.7.1=cuda*
  - cudatoolkit=10.2*
  - astra-toolbox=1.9.9.dev4
  - requests=2.25.1
  - h5py=3.1.0
  - sarepy=2020.07
  - psutil=5.7.3
  # ^^ from meta.yml
  - cil
  - cil-astra
  - ccpi-regulariser
  - tomophantom
  - pip
  - pip:
      # For running
      - pyqt5==5.15
      - pyqtgraph==0.11
      - jenkspy==0.2.0
      # For developement
      - pytest==6.2.1
      - pytest-cov==2.10.1
      - coveralls==2.2.0
      - yapf==0.30.0
      - mypy==0.790
      - flake8==3.8.4
      - testfixtures==6.17.0
      - coverage==5.3
      - gitpython==3.1.11
      - pylint==2.6.0
      - sphinx==3.3.1
      - git+https://github.com/samtygier-stfc/sphinx-multiversion.git@prebuild_command
      - pytest-randomly==3.5.0
      - pytest-xdist==2.2.0
      - pytest-repeat==0.9.1
      - psutil==5.7.3
      - isort==5.6.4
      - eyes-images==4.15.0
